# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /work/submit/abelley/imsrg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /work/submit/abelley/imsrg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /work/submit/abelley/imsrg/CMakeFiles /work/submit/abelley/imsrg//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /work/submit/abelley/imsrg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pyIMSRG

# Build rule for target.
pyIMSRG: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pyIMSRG
.PHONY : pyIMSRG

# fast build rule for target.
pyIMSRG/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pyIMSRG.dir/build.make CMakeFiles/pyIMSRG.dir/build
.PHONY : pyIMSRG/fast

#=============================================================================
# Target rules for targets named AngMom

# Build rule for target.
AngMom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AngMom
.PHONY : AngMom

# fast build rule for target.
AngMom/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/AngMom.dir/build.make src/CMakeFiles/AngMom.dir/build
.PHONY : AngMom/fast

#=============================================================================
# Target rules for targets named AngMomCache

# Build rule for target.
AngMomCache: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AngMomCache
.PHONY : AngMomCache

# fast build rule for target.
AngMomCache/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/AngMomCache.dir/build.make src/CMakeFiles/AngMomCache.dir/build
.PHONY : AngMomCache/fast

#=============================================================================
# Target rules for targets named IMSRGProfiler

# Build rule for target.
IMSRGProfiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IMSRGProfiler
.PHONY : IMSRGProfiler

# fast build rule for target.
IMSRGProfiler/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/IMSRGProfiler.dir/build.make src/CMakeFiles/IMSRGProfiler.dir/build
.PHONY : IMSRGProfiler/fast

#=============================================================================
# Target rules for targets named ModelSpace

# Build rule for target.
ModelSpace: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ModelSpace
.PHONY : ModelSpace

# fast build rule for target.
ModelSpace/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ModelSpace.dir/build.make src/CMakeFiles/ModelSpace.dir/build
.PHONY : ModelSpace/fast

#=============================================================================
# Target rules for targets named TwoBodyME

# Build rule for target.
TwoBodyME: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TwoBodyME
.PHONY : TwoBodyME

# fast build rule for target.
TwoBodyME/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/TwoBodyME.dir/build.make src/CMakeFiles/TwoBodyME.dir/build
.PHONY : TwoBodyME/fast

#=============================================================================
# Target rules for targets named ThreeLegME

# Build rule for target.
ThreeLegME: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ThreeLegME
.PHONY : ThreeLegME

# fast build rule for target.
ThreeLegME/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ThreeLegME.dir/build.make src/CMakeFiles/ThreeLegME.dir/build
.PHONY : ThreeLegME/fast

#=============================================================================
# Target rules for targets named ThreeBodyStorage

# Build rule for target.
ThreeBodyStorage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ThreeBodyStorage
.PHONY : ThreeBodyStorage

# fast build rule for target.
ThreeBodyStorage/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ThreeBodyStorage.dir/build.make src/CMakeFiles/ThreeBodyStorage.dir/build
.PHONY : ThreeBodyStorage/fast

#=============================================================================
# Target rules for targets named ThreeBodyStorage_pn

# Build rule for target.
ThreeBodyStorage_pn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ThreeBodyStorage_pn
.PHONY : ThreeBodyStorage_pn

# fast build rule for target.
ThreeBodyStorage_pn/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ThreeBodyStorage_pn.dir/build.make src/CMakeFiles/ThreeBodyStorage_pn.dir/build
.PHONY : ThreeBodyStorage_pn/fast

#=============================================================================
# Target rules for targets named ThreeBodyStorage_no2b

# Build rule for target.
ThreeBodyStorage_no2b: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ThreeBodyStorage_no2b
.PHONY : ThreeBodyStorage_no2b

# fast build rule for target.
ThreeBodyStorage_no2b/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ThreeBodyStorage_no2b.dir/build.make src/CMakeFiles/ThreeBodyStorage_no2b.dir/build
.PHONY : ThreeBodyStorage_no2b/fast

#=============================================================================
# Target rules for targets named ThreeBodyStorage_mono

# Build rule for target.
ThreeBodyStorage_mono: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ThreeBodyStorage_mono
.PHONY : ThreeBodyStorage_mono

# fast build rule for target.
ThreeBodyStorage_mono/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ThreeBodyStorage_mono.dir/build.make src/CMakeFiles/ThreeBodyStorage_mono.dir/build
.PHONY : ThreeBodyStorage_mono/fast

#=============================================================================
# Target rules for targets named ThreeBodyStorage_iso

# Build rule for target.
ThreeBodyStorage_iso: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ThreeBodyStorage_iso
.PHONY : ThreeBodyStorage_iso

# fast build rule for target.
ThreeBodyStorage_iso/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ThreeBodyStorage_iso.dir/build.make src/CMakeFiles/ThreeBodyStorage_iso.dir/build
.PHONY : ThreeBodyStorage_iso/fast

#=============================================================================
# Target rules for targets named ThreeBodyME

# Build rule for target.
ThreeBodyME: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ThreeBodyME
.PHONY : ThreeBodyME

# fast build rule for target.
ThreeBodyME/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ThreeBodyME.dir/build.make src/CMakeFiles/ThreeBodyME.dir/build
.PHONY : ThreeBodyME/fast

#=============================================================================
# Target rules for targets named Operator

# Build rule for target.
Operator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Operator
.PHONY : Operator

# fast build rule for target.
Operator/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Operator.dir/build.make src/CMakeFiles/Operator.dir/build
.PHONY : Operator/fast

#=============================================================================
# Target rules for targets named Version

# Build rule for target.
Version: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Version
.PHONY : Version

# fast build rule for target.
Version/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Version.dir/build.make src/CMakeFiles/Version.dir/build
.PHONY : Version/fast

#=============================================================================
# Target rules for targets named ReadWrite

# Build rule for target.
ReadWrite: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ReadWrite
.PHONY : ReadWrite

# fast build rule for target.
ReadWrite/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ReadWrite.dir/build.make src/CMakeFiles/ReadWrite.dir/build
.PHONY : ReadWrite/fast

#=============================================================================
# Target rules for targets named BCH

# Build rule for target.
BCH: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BCH
.PHONY : BCH

# fast build rule for target.
BCH/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/BCH.dir/build.make src/CMakeFiles/BCH.dir/build
.PHONY : BCH/fast

#=============================================================================
# Target rules for targets named IMSRGSolver

# Build rule for target.
IMSRGSolver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IMSRGSolver
.PHONY : IMSRGSolver

# fast build rule for target.
IMSRGSolver/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/IMSRGSolver.dir/build.make src/CMakeFiles/IMSRGSolver.dir/build
.PHONY : IMSRGSolver/fast

#=============================================================================
# Target rules for targets named IMSRGSolverPV

# Build rule for target.
IMSRGSolverPV: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IMSRGSolverPV
.PHONY : IMSRGSolverPV

# fast build rule for target.
IMSRGSolverPV/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/IMSRGSolverPV.dir/build.make src/CMakeFiles/IMSRGSolverPV.dir/build
.PHONY : IMSRGSolverPV/fast

#=============================================================================
# Target rules for targets named Commutator232

# Build rule for target.
Commutator232: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Commutator232
.PHONY : Commutator232

# fast build rule for target.
Commutator232/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Commutator232.dir/build.make src/CMakeFiles/Commutator232.dir/build
.PHONY : Commutator232/fast

#=============================================================================
# Target rules for targets named TensorCommutators

# Build rule for target.
TensorCommutators: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TensorCommutators
.PHONY : TensorCommutators

# fast build rule for target.
TensorCommutators/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/TensorCommutators.dir/build.make src/CMakeFiles/TensorCommutators.dir/build
.PHONY : TensorCommutators/fast

#=============================================================================
# Target rules for targets named IMSRG3Commutators

# Build rule for target.
IMSRG3Commutators: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IMSRG3Commutators
.PHONY : IMSRG3Commutators

# fast build rule for target.
IMSRG3Commutators/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/IMSRG3Commutators.dir/build.make src/CMakeFiles/IMSRG3Commutators.dir/build
.PHONY : IMSRG3Commutators/fast

#=============================================================================
# Target rules for targets named FactorizedDoubleCommutator

# Build rule for target.
FactorizedDoubleCommutator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FactorizedDoubleCommutator
.PHONY : FactorizedDoubleCommutator

# fast build rule for target.
FactorizedDoubleCommutator/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/FactorizedDoubleCommutator.dir/build.make src/CMakeFiles/FactorizedDoubleCommutator.dir/build
.PHONY : FactorizedDoubleCommutator/fast

#=============================================================================
# Target rules for targets named DaggerCommutators

# Build rule for target.
DaggerCommutators: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DaggerCommutators
.PHONY : DaggerCommutators

# fast build rule for target.
DaggerCommutators/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/DaggerCommutators.dir/build.make src/CMakeFiles/DaggerCommutators.dir/build
.PHONY : DaggerCommutators/fast

#=============================================================================
# Target rules for targets named Commutator

# Build rule for target.
Commutator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Commutator
.PHONY : Commutator

# fast build rule for target.
Commutator/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Commutator.dir/build.make src/CMakeFiles/Commutator.dir/build
.PHONY : Commutator/fast

#=============================================================================
# Target rules for targets named DarkMatterNREFT

# Build rule for target.
DarkMatterNREFT: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DarkMatterNREFT
.PHONY : DarkMatterNREFT

# fast build rule for target.
DarkMatterNREFT/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/DarkMatterNREFT.dir/build.make src/CMakeFiles/DarkMatterNREFT.dir/build
.PHONY : DarkMatterNREFT/fast

#=============================================================================
# Target rules for targets named Jacobi3BME

# Build rule for target.
Jacobi3BME: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Jacobi3BME
.PHONY : Jacobi3BME

# fast build rule for target.
Jacobi3BME/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Jacobi3BME.dir/build.make src/CMakeFiles/Jacobi3BME.dir/build
.PHONY : Jacobi3BME/fast

#=============================================================================
# Target rules for targets named HartreeFock

# Build rule for target.
HartreeFock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HartreeFock
.PHONY : HartreeFock

# fast build rule for target.
HartreeFock/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/HartreeFock.dir/build.make src/CMakeFiles/HartreeFock.dir/build
.PHONY : HartreeFock/fast

#=============================================================================
# Target rules for targets named Pwd

# Build rule for target.
Pwd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pwd
.PHONY : Pwd

# fast build rule for target.
Pwd/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Pwd.dir/build.make src/CMakeFiles/Pwd.dir/build
.PHONY : Pwd/fast

#=============================================================================
# Target rules for targets named M0nu

# Build rule for target.
M0nu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 M0nu
.PHONY : M0nu

# fast build rule for target.
M0nu/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/M0nu.dir/build.make src/CMakeFiles/M0nu.dir/build
.PHONY : M0nu/fast

#=============================================================================
# Target rules for targets named imsrg_util

# Build rule for target.
imsrg_util: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imsrg_util
.PHONY : imsrg_util

# fast build rule for target.
imsrg_util/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/imsrg_util.dir/build.make src/CMakeFiles/imsrg_util.dir/build
.PHONY : imsrg_util/fast

#=============================================================================
# Target rules for targets named Generator

# Build rule for target.
Generator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Generator
.PHONY : Generator

# fast build rule for target.
Generator/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Generator.dir/build.make src/CMakeFiles/Generator.dir/build
.PHONY : Generator/fast

#=============================================================================
# Target rules for targets named GeneratorPV

# Build rule for target.
GeneratorPV: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GeneratorPV
.PHONY : GeneratorPV

# fast build rule for target.
GeneratorPV/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/GeneratorPV.dir/build.make src/CMakeFiles/GeneratorPV.dir/build
.PHONY : GeneratorPV/fast

#=============================================================================
# Target rules for targets named HFMBPT

# Build rule for target.
HFMBPT: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HFMBPT
.PHONY : HFMBPT

# fast build rule for target.
HFMBPT/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/HFMBPT.dir/build.make src/CMakeFiles/HFMBPT.dir/build
.PHONY : HFMBPT/fast

#=============================================================================
# Target rules for targets named RPA

# Build rule for target.
RPA: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RPA
.PHONY : RPA

# fast build rule for target.
RPA/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/RPA.dir/build.make src/CMakeFiles/RPA.dir/build
.PHONY : RPA/fast

#=============================================================================
# Target rules for targets named ReferenceImplementations

# Build rule for target.
ReferenceImplementations: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ReferenceImplementations
.PHONY : ReferenceImplementations

# fast build rule for target.
ReferenceImplementations/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ReferenceImplementations.dir/build.make src/CMakeFiles/ReferenceImplementations.dir/build
.PHONY : ReferenceImplementations/fast

#=============================================================================
# Target rules for targets named UnitTest

# Build rule for target.
UnitTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UnitTest
.PHONY : UnitTest

# fast build rule for target.
UnitTest/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/UnitTest.dir/build.make src/CMakeFiles/UnitTest.dir/build
.PHONY : UnitTest/fast

#=============================================================================
# Target rules for targets named imsrg++

# Build rule for target.
imsrg++: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imsrg++
.PHONY : imsrg++

# fast build rule for target.
imsrg++/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/imsrg++.dir/build.make src/CMakeFiles/imsrg++.dir/build
.PHONY : imsrg++/fast

#=============================================================================
# Target rules for targets named IMSRGBoostZip

# Build rule for target.
IMSRGBoostZip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IMSRGBoostZip
.PHONY : IMSRGBoostZip

# fast build rule for target.
IMSRGBoostZip/fast:
	$(MAKE) $(MAKESILENT) -f extern/boost_src/CMakeFiles/IMSRGBoostZip.dir/build.make extern/boost_src/CMakeFiles/IMSRGBoostZip.dir/build
.PHONY : IMSRGBoostZip/fast

src/pyIMSRG.o: src/pyIMSRG.cc.o
.PHONY : src/pyIMSRG.o

# target to build an object file
src/pyIMSRG.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pyIMSRG.dir/build.make CMakeFiles/pyIMSRG.dir/src/pyIMSRG.cc.o
.PHONY : src/pyIMSRG.cc.o

src/pyIMSRG.i: src/pyIMSRG.cc.i
.PHONY : src/pyIMSRG.i

# target to preprocess a source file
src/pyIMSRG.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pyIMSRG.dir/build.make CMakeFiles/pyIMSRG.dir/src/pyIMSRG.cc.i
.PHONY : src/pyIMSRG.cc.i

src/pyIMSRG.s: src/pyIMSRG.cc.s
.PHONY : src/pyIMSRG.s

# target to generate assembly for a file
src/pyIMSRG.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pyIMSRG.dir/build.make CMakeFiles/pyIMSRG.dir/src/pyIMSRG.cc.s
.PHONY : src/pyIMSRG.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... AngMom"
	@echo "... AngMomCache"
	@echo "... BCH"
	@echo "... Commutator"
	@echo "... Commutator232"
	@echo "... DaggerCommutators"
	@echo "... DarkMatterNREFT"
	@echo "... FactorizedDoubleCommutator"
	@echo "... Generator"
	@echo "... GeneratorPV"
	@echo "... HFMBPT"
	@echo "... HartreeFock"
	@echo "... IMSRG3Commutators"
	@echo "... IMSRGBoostZip"
	@echo "... IMSRGProfiler"
	@echo "... IMSRGSolver"
	@echo "... IMSRGSolverPV"
	@echo "... Jacobi3BME"
	@echo "... M0nu"
	@echo "... ModelSpace"
	@echo "... Operator"
	@echo "... Pwd"
	@echo "... RPA"
	@echo "... ReadWrite"
	@echo "... ReferenceImplementations"
	@echo "... TensorCommutators"
	@echo "... ThreeBodyME"
	@echo "... ThreeBodyStorage"
	@echo "... ThreeBodyStorage_iso"
	@echo "... ThreeBodyStorage_mono"
	@echo "... ThreeBodyStorage_no2b"
	@echo "... ThreeBodyStorage_pn"
	@echo "... ThreeLegME"
	@echo "... TwoBodyME"
	@echo "... UnitTest"
	@echo "... Version"
	@echo "... imsrg++"
	@echo "... imsrg_util"
	@echo "... pyIMSRG"
	@echo "... src/pyIMSRG.o"
	@echo "... src/pyIMSRG.i"
	@echo "... src/pyIMSRG.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

